export const data = [
  {
    collection: "PCa_Bx_3Dpathology",
    collection_url: "10.7937/44MA-GX21",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:pca_bx_3d",
    download: "Download",
    download_url: "361?passcode=2b36e2d389e0d0adbf55cd01dd33f05e8d7d0a59",
    cancer_type: "Prostate Cancer",
    location: "Prostate",
    species: "Human",
    subject: 50,
    data_format: "HDF5, TIFF",
    supporting_data: "Clinical",
    manufacturer: "",
    modality: "Hierarchical Data Format 5, Tiff stack",
    protocol: "Toluidine-eosin stain",
    par: "",
    magnification: "",
    size: 3787,
    access: "Public",
    updated: "2023-03-17",
  },
  {
    collection: "UPENN-GBM",
    collection_url: "10.7937/TCIA.709X-DN49",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:upenn_gbm",
    download: "Download",
    download_url: "332?passcode=47b546b57f9737fed715a077ec0bb2f2678f8877",
    cancer_type: "Glioblastoma",
    location: "Brain",
    species: "Human",
    subject: 34,
    data_format: "NDPI",
    supporting_data: "N/A",
    manufacturer: "Hamamatsu",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.230,0.230)mpp",
    magnification: "",
    size: 149,
    access: "Public",
    updated: "2022-10-24",
  },
  {
    collection: "Hungarian-Colorectal-Screening",
    collection_url: "10.7937/tcia.9cjf-0127",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:hungarian_colorectal_screening",
    download: "Download",
    download_url: "330?passcode=1daa435815917f7497f97b4811180e1bc7a59515",
    cancer_type: "Colorectal Cancer",
    location: "Colon",
    species: "Human",
    subject: 200,
    data_format: "MRXS",
    supporting_data: "Clinical, Image Analyses",
    manufacturer: "3DHistech",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.121,0.121)mpp",
    magnification: "40x",
    size: 392,
    access: "Saltz-Lab",
    updated: "2022-09-19",
  },
  {
    collection: "CMB-CRC",
    collection_url: "10.7937/DJG7-GZ87",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/biobank_metadata_page_first50_4.json&filterState=[{"id":"TCIA_Collection","title":"Collection","field":"TCIA_Collection","operation":"eq","values":"CMB-CRC"}]',
    download: "Download",
    download_url: "312?passcode=802689a7d06cc00fbb766043eeafef8de6c91d8b",
    cancer_type: "Colorectal Cancer",
    location: "Colon",
    species: "Human",
    subject: 10,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.252,0.252)mpp",
    magnification: "40x",
    size: 13.8,
    access: "Public",
    updated: "2022-08-12",
  },
  {
    collection: "CMB-GEC",
    collection_url: "10.7937/E7KH-R486",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/biobank_metadata_page_first50_4.json&filterState=[{"id":"TCIA_Collection","title":"Collection","field":"TCIA_Collection","operation":"eq","values":"CMB-GEC"}]',
    download: "Download",
    download_url: "313?passcode=f3b76cfbdf7f6ecfb5f9b507a433cb304ab4764c",
    cancer_type: "Gastroesophageal Cancer",
    location: "Esophagus",
    species: "Human",
    subject: 1,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.252,0.252)mpp",
    magnification: "40x",
    size: 0.103,
    access: "Saltz-Lab",
    updated: "2022-08-12",
  },
  {
    collection: "CMB-LCA",
    collection_url: "10.7937/3CX3-S132",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/biobank_metadata_page_first50_4.json&filterState=[{"id":"TCIA_Collection","title":"Collection","field":"TCIA_Collection","operation":"eq","values":"CMB-LCA"}]',
    download: "Download",
    download_url: "314?passcode=5ab6a15b566748065c7f780efa7dd0374d91bfe7",
    cancer_type: "Lung Cancer",
    location: "Lung",
    species: "Human",
    subject: 9,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.252,0.252)mpp",
    magnification: "40x",
    size: 5.4,
    access: "Public",
    updated: "2022-08-12",
  },
  {
    collection: "CMB-MEL",
    collection_url: "10.7937/GWSP-WH72",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/biobank_metadata_page_first50_4.json&filterState=[{"id":"TCIA_Collection","title":"Collection","field":"TCIA_Collection","operation":"eq","values":"CMB-MEL"}]',
    download: "Download",
    download_url: "315?passcode=5cb6e4498dacceb214a7973caf5e2f45908702af",
    cancer_type: "Melanoma",
    location: "Various",
    species: "Human",
    subject: 15,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.252,0.252)mpp",
    magnification: "40x",
    size: 35.7,
    access: "Public",
    updated: "2022-08-12",
  },
  {
    collection: "CMB-MML",
    collection_url: "10.7937/SZKB-SW39",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/biobank_metadata_page_first50_4.json&filterState=[{"id":"TCIA_Collection","title":"Collection","field":"TCIA_Collection","operation":"eq","values":"CMB-MML"}]',
    download: "Download",
    download_url: "316?passcode=0a97a7fe03d7642341f513fabbb54c56450597d8",
    cancer_type: "Multiple Myeloma",
    location: "Blood, Bone",
    species: "Human",
    subject: 1,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.252,0.252)mpp",
    magnification: "40x",
    size: 0.29,
    access: "Saltz-Lab",
    updated: "2022-08-12",
  },
  {
    collection: "CMB-PCA",
    collection_url: "10.7937/25T7-6Y12",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/biobank_metadata_page_first50_4.json&filterState=[{"id":"TCIA_Collection","title":"Collection","field":"TCIA_Collection","operation":"eq","values":"CMB-PCA"}]',
    download: "Download",
    download_url: "317?passcode=ee007f57d51338561d7d68532503736eebde05af",
    cancer_type: "Prostate Cancer",
    location: "Prostate",
    species: "Human",
    subject: 3,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.252,0.252)mpp",
    magnification: "40x",
    size: 0.582,
    access: "Public",
    updated: "2022-08-12",
  },
  {
    collection: "HER2 tumor ROIs",
    collection_url: "10.7937/E65C-AM96",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:her2_roi",
    download: "Download",
    download_url: "311?passcode=dabde05cb596923338b717013b335f5258a9adb3",
    cancer_type: "HER2+ Breast Cancer",
    location: "Breast",
    species: "Human",
    subject: 273,
    data_format: "SVS",
    supporting_data: "Image Analyses",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.499,0.499)mpp",
    magnification: "20x",
    size: 40,
    access: "Public",
    updated: "2022-08-03",
  },
  {
    collection: "DLBCL-morphology",
    collection_url: "10.7937/NVA3-N783",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:dlbcl_morph",
    download: "Download",
    download_url: "269?passcode=5796b1ab3f7d17d13ab1df035c15a6835fd9c59a",
    cancer_type: "Diffuse Large B-Cell Lymphoma",
    location: "Lymph Node",
    species: "Human",
    subject: 209,
    data_format: "SVS",
    supporting_data: "Clinical, Image Analyses",
    manufacturer: "Leica",
    modality: "Tissue Microarray, Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.254,0.254)mpp",
    magnification: "",
    size: 350,
    access: "Public",
    updated: "2022-04-28",
  },
  {
    collection: "CATCH",
    collection_url: "10.7937/TCIA.2M93-FX66",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:catch",
    download: "Download",
    download_url: "243?passcode=5a86450fa8c10a946ceab112b59280d0bd964b16",
    cancer_type: "Skin Cancer",
    location: "Skin",
    species: "Canine",
    subject: 282,
    data_format: "SVS",
    supporting_data: "Image Analyses",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.253,0.253)mpp",
    magnification: "",
    size: 522,
    access: "Public",
    updated: "2022-01-13",
  },
  {
    collection: "Ovarian Bevacizumab Response",
    collection_url: "10.7937/TCIA.985G-EY35",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:ovarian_bevacizumab_response",
    download: "Download",
    download_url: "221?passcode=15bbd6ad41dc98fff70949c70f4b9ef55c954cca",
    cancer_type: "Ovarian Cancer",
    location: "Ovary",
    species: "Human",
    subject: 78,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.027,0.020)mpp",
    magnification: "20x",
    size: 253.8,
    access: "Public",
    updated: "2021-12-17",
  },
  {
    collection: "Bone-Marrow-Cytomorphology",
    collection_url: "10.7937/TCIA.AXH3-T579",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:bone",
    download: "Download",
    download_url: "236?passcode=43cdf773491be7dd516e01db360c43b1ae94276c",
    cancer_type: "Leukemia & Lymphoma Cancers",
    location: "Marrow",
    species: "Human",
    subject: 945,
    data_format: "JPG",
    supporting_data: "N/A",
    manufacturer: "Zeiss",
    modality: "Photomicrograph",
    protocol: "May-Grunwald-Giemsa stain",
    par: "(0.086,0.086)mpp",
    magnification: "40x",
    size: 6.8,
    access: "Public",
    updated: "2021-12-06",
  },
  {
    collection: "NLST",
    collection_url: "10.7937/TCIA.HMQ8-J677",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:nlst",
    download: "Download",
    download_url: "208?passcode=e89b6c607f2a8b50f76e06f1735c157357cdfdaf",
    cancer_type: "Lung Cancer",
    location: "Chest",
    species: "Human",
    subject: 451,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "",
    modality: "Tissue Microarray",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.250,0.250)mpp",
    magnification: "",
    size: 775,
    access: "Public",
    updated: "2021-09-24",
  },
  {
    collection: "SLN-Breast",
    collection_url: "10.7937/tcia.2019.3xbn2jcc",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:sln_breast",
    download: "Download",
    download_url: "71?passcode=79b9a8885b0115c3c0d061d3954d2f78087637e5",
    cancer_type: "Breast Cancer",
    location: "Breast",
    species: "Human",
    subject: 78,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.501,0.501)mpp",
    magnification: "20x",
    size: 53,
    access: "Public",
    updated: "2021-03-04",
  },
  {
    collection: "NADT-Prostate",
    collection_url: "10.7937/TCIA.JHQD-FR46",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:nadt_prostate",
    download: "Download",
    download_url: "247?passcode=bd1f9a104cbb48595f02889775bf41c46ec4ce78",
    cancer_type: "Prostate Cancer",
    location: "Prostate",
    species: "Human",
    subject: 37,
    data_format: "TIFF",
    supporting_data: "Clinical",
    manufacturer: "Zeiss",
    modality: "",
    protocol: "IHC stain, Hematoxylin and eosin stain, LCM",
    par: "(0.453,0.453)mpp",
    magnification: "20x",
    size: 1400,
    access: "Public",
    updated: "2021-02-11",
  },
  {
    collection: "CPTAC-PDA",
    collection_url: "10.7937/k9/tcia.2018.sc20fo18",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"PDA"}]',
    download: "Download",
    download_url: "28?passcode=1dd55bbee4063a3901315e94a6e92806eba11e92",
    cancer_type: "Ductal Adenocarcinoma",
    location: "Pancreas",
    species: "Human",
    subject: 168,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 88,
    access: "Public",
    updated: "2021-02-04",
  },
  {
    collection: "CPTAC-BRCA",
    collection_url: "10.7937/TCIA.CAEM-YS80",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:cptac_brca",
    download: "Download",
    download_url: "69?passcode=25833f7cfcdec54d34a7b19fd3fb4bfe328bf923",
    cancer_type: "Breast Cancer",
    location: "Breast",
    species: "Human",
    subject: 134,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.250,0.250)mpp",
    magnification: "40x",
    size: 113.29,
    access: "Public",
    updated: "2021-02-02",
  },
  {
    collection: "CPTAC-COAD",
    collection_url: "10.7937/TCIA.YZWQ-ZZ63",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:cptac_coad",
    download: "Download",
    download_url: "68?passcode=4923758254bc7d015e8f6cc4175ee25e388c36dd",
    cancer_type: "Colon Cancer",
    location: "Colon",
    species: "Human",
    subject: 106,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.250,0.250)mpp",
    magnification: "40x",
    size: 66.69,
    access: "Public",
    updated: "2021-02-02",
  },
  {
    collection: "CPTAC-OV",
    collection_url: "10.7937/TCIA.ZS4A-JD58",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:cptac_ov",
    download: "Download",
    download_url: "56?passcode=939306e2a7bc58fbc19e5085deb4128b6b268d20",
    cancer_type: "Ovarian Cancer",
    location: "Ovary",
    species: "Human",
    subject: 102,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.250,0.250)mpp",
    magnification: "40x",
    size: 54.64,
    access: "Public",
    updated: "2021-02-02",
  },
  {
    collection: "CPTAC-LSCC",
    collection_url: "10.7937/k9/tcia.2018.6emub5l2",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"LSCC"}]',
    download: "Download",
    download_url: "26?passcode=0a463fb5c18b6b51f91f04638084fc18ff59348f",
    cancer_type: "Squamous Cell Carcinoma",
    location: "Lung",
    species: "Human",
    subject: 212,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 414,
    access: "Public",
    updated: "2021-01-23",
  },
  {
    collection: "Post-NAT-BRCA",
    collection_url: "10.7937/TCIA.2019.4YIBTJNO",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:post_nat_brca",
    download: "Download",
    download_url: "79?passcode=1ae23d3c2a1f2f1ff08cab9ddf49c2d0f906100a",
    cancer_type: "Breast Cancer",
    location: "Breast",
    species: "Human",
    subject: 64,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.502,0.502)mpp",
    magnification: "20x",
    size: 43,
    access: "Public",
    updated: "2021-01-09",
  },
  {
    collection: "HNSCC-mIF-mIHC-comparison",
    collection_url: "10.7937/TCIA.2020.T90F-WB82",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:hnscc_mif_mihc_comparison",
    download: "Download",
    download_url: "74?passcode=56970ac8fccfb0cdb926271492d7f3ab3ea8721c",
    cancer_type: "Head and Neck Cancer",
    location: "Head-Neck",
    species: "Human",
    subject: 8,
    data_format: "TIFF",
    supporting_data: "Image Analyses",
    manufacturer: "",
    modality: "Immunofluorescence/Immunohistochemistry",
    protocol: "N/A",
    par: "",
    magnification: "20x",
    size: 8.96,
    access: "Public",
    updated: "2020-07-31",
  },
  {
    collection: "CPTAC-CM",
    collection_url: "10.7937/k9/tcia.2018.odu24gze",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"CM"}]',
    download: "Download",
    download_url: "21?passcode=26b1b8180593cc26c6716e8f266e4125bd420cd2",
    cancer_type: "Cutaneous Melanoma",
    location: "Skin",
    species: "Human",
    subject: 94,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 107,
    access: "Public",
    updated: "2020-06-30",
  },
  {
    collection: "CPTAC-HNSCC",
    collection_url: "10.7937/K9/TCIA.2018.UW45NH81",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"HNSCC"}]',
    download: "Download",
    download_url: "25?passcode=9907cd5111477f668c1abb9d7e6baa260ec550ef",
    cancer_type: "Head and Neck Cancer",
    location: "Head-Neck",
    species: "Human",
    subject: 112,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 97,
    access: "Public",
    updated: "2020-06-30",
  },
  {
    collection: "CPTAC-AML",
    collection_url: "10.7937/tcia.2019.b6foe619",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"AML"}]',
    download: "Download",
    download_url: "19?passcode=b8d21401892e1d19604b3648346eafdfd7857473",
    cancer_type: "Acute Myeloid Leukemia",
    location: "Marrow, Blood",
    species: "Human",
    subject: 88,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.246,0.246)mpp",
    magnification: "40x",
    size: 378,
    access: "Public",
    updated: "2020-04-28",
  },
  {
    collection: "CRC_FFPE-CODEX_CellNeighs",
    collection_url: "10.7937/TCIA.2020.FQN0-0326",
    view: "",
    camic_url: "",
    download: "Download",
    download_url: "18?passcode=2442106c1a03f1b911073d97f323130a67aa5d54",
    cancer_type: "Colorectal Cancer",
    location: "Colon",
    species: "Human",
    subject: 35,
    data_format: "TIFF",
    supporting_data: "Clinical, Image Analyses",
    manufacturer: "3DHistech",
    modality: "Immunofluorescence",
    protocol: "IHC, CODEX, Hematoxylin and eosin staining",
    par: "",
    magnification: "20x",
    size: 2000,
    access: "Public",
    updated: "2020-04-09",
  },
  {
    collection: "CPTAC-GBM",
    collection_url: "10.7937/k9/tcia.2018.3rje41q1",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"GBM"}]',
    download: "Download",
    download_url: "24?passcode=1e867885ccc05efb745255d778d573262d46101d",
    cancer_type: "Glioblastoma Multiforme",
    location: "Brain",
    species: "Human",
    subject: 189,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 87,
    access: "Public",
    updated: "2020-03-31",
  },
  {
    collection: "CPTAC-LUAD",
    collection_url: "10.7937/k9/tcia.2018.pat12tbs",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"LUAD"}]',
    download: "Download",
    download_url: "27?passcode=489c1a60942a14311602196fd8f303ba6cc184a6",
    cancer_type: "Adenocarcinoma",
    location: "Lung",
    species: "Human",
    subject: 244,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 425,
    access: "Public",
    updated: "2020-03-31",
  },
  {
    collection: "CPTAC-SAR",
    collection_url: "10.7937/TCIA.2019.9bt23r95",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"SAR"}]',
    download: "Download",
    download_url: "29?passcode=4caeb3cb49756a0308203e2a9388de5d7508c675",
    cancer_type: "Sarcomas",
    location: "Various (11 locations)",
    species: "Human",
    subject: 94,
    data_format: "SVS",
    supporting_data: "Clinical",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 69,
    access: "Public",
    updated: "2020-03-31",
  },
  {
    collection: "CPTAC-UCEC",
    collection_url: "10.7937/k9/tcia.2018.3r3juisw",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"UCEC"}]',
    download: "Download",
    download_url: "23?passcode=51c1486da8953eafd7cb844c82957da833144647",
    cancer_type: "Corpus Edometrial Carcinoma",
    location: "Uterus",
    species: "Human",
    subject: 250,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 154,
    access: "Public",
    updated: "2020-03-31",
  },
  {
    collection: "ICDC-Glioma",
    collection_url: "10.7937/TCIA.SVQT-Q016",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:icdc_glioma01",
    download: "Download",
    download_url: "52?passcode=3e2f243fcda898fa072867073f262a795d21b930",
    cancer_type: "Glioma",
    location: "Head",
    species: "Canine",
    subject: 78,
    data_format: "SVS",
    supporting_data: "N/A",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.251,0.251)mpp",
    magnification: "40x",
    size: 172,
    access: "Public",
    updated: "2020-01-09",
  },
  {
    collection: "Lung Fused-CT-Pathology",
    collection_url: "10.7937/K9/TCIA.2018.SMT36LPN",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:lung_fused_ct_pathology",
    download: "Download",
    download_url: "80?passcode=2e2eb188bbddd4b7d145fde0f6696493cf8a229e",
    cancer_type: "Lung Cancer",
    location: "Lung",
    species: "Human",
    subject: 6,
    data_format: "TIFF",
    supporting_data: "Image Analyses",
    manufacturer: "",
    modality: "",
    protocol: "N/A",
    par: "",
    magnification: "",
    size: 21.3,
    access: "Public",
    updated: "2019-11-15",
  },
  {
    collection: "AML-Cytomorphology_LMU",
    collection_url: "10.7937/tcia.2019.36f5o9ld",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:aml_cytomorphology_lmu",
    download: "Download",
    download_url: "77?passcode=a6be8bf0a97ddb34fc0913f37b8180d8f7d616a7",
    cancer_type: "Acute Myeloid Leukemia",
    location: "Blood",
    species: "Human",
    subject: 200,
    data_format: "TIFF",
    supporting_data: "Image Analyses",
    manufacturer: "Precipoint",
    modality: "Photomicrograph",
    protocol: "N/A",
    par: "(0.290,0.290)mpp",
    magnification: "100x",
    size: 11,
    access: "Public",
    updated: "2019-10-28",
  },
  {
    collection: "CPTAC-CCRCC",
    collection_url: "10.7937/k9/tcia.2018.oblamn27",
    view: "View",
    camic_url:
      'https://pathdb.cancerimagingarchive.net/eaglescope/dist/?configurl=/system/files/collectionmetadata/202208/cptac_metadata_page_0.json&filterState=[{"id":"Tumor","title":"Tumor","field":"Tumor","operation":"eq","values":"CCRCC"}]',
    download: "Download",
    download_url: "226?passcode=9cb811d096453ac5468a49352b018ccec8526376",
    cancer_type: "Clear Cell Carcinoma",
    location: "Kidney",
    species: "Human",
    subject: 222,
    data_format: "SVS",
    supporting_data: "Clinical, Genomics, Proteomics",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.494,0.494)mpp",
    magnification: "40x",
    size: 190,
    access: "Public",
    updated: "2019-09-30",
  },
  {
    collection: "TCGA-TIL-WSI",
    collection_url: "10.7937/K9/TCIA.2018.Y75F9W1",
    view: "View",
    camic_url: "https://cancerimagingarchive.net/datascope/TCGA_TilMap/",
    download: "",
    download_url: "",
    cancer_type: "Various",
    location: "Various",
    species: "Human",
    subject: 1842,
    data_format: "SVS",
    supporting_data: "Image Analyses, Clinical, Genomics",
    manufacturer: "",
    modality: "",
    protocol: "N/A",
    par: "",
    magnification: "",
    size: "",
    access: "Public",
    updated: "2019-08-30",
  },
  {
    collection: "C-NMC 2019",
    collection_url: "10.7937/tcia.2019.dc64i46r",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:c_nmc_2019",
    download: "Download",
    download_url: "75?passcode=ebf6e585c2b531f41fbcd2b9cfd7b15303eeca80",
    cancer_type: "Leukemia",
    location: "Blood, Bone",
    species: "Human",
    subject: 118,
    data_format: "BMP",
    supporting_data: "N/A",
    manufacturer: "",
    modality: "Raster",
    protocol: "Jenner-Giemsa stain",
    par: "",
    magnification: "",
    size: 10.44,
    access: "Public",
    updated: "2019-05-28",
  },
  {
    collection: "MiMM_SBILab",
    collection_url: "10.7937/tcia.2019.pnn6aypl",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:mimm_sbilab",
    download: "Download",
    download_url: "67?passcode=80a45e497421c180f037e4044ae6c38f798015eb",
    cancer_type: "Multiple Myeloma",
    location: "Bone",
    species: "Human",
    subject: 5,
    data_format: "BMP",
    supporting_data: "Image Analyses",
    manufacturer: "Nikon",
    modality: "Raster",
    protocol: "Jenner-Giemsa stain",
    par: "",
    magnification: "1000x",
    size: 1.27,
    access: "Public",
    updated: "2019-05-28",
  },
  {
    collection: "SN-AM",
    collection_url: "10.7937/tcia.2019.of2w8lxr",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:sn_am",
    download: "Download",
    download_url: "73?passcode=9b10a5486bb8ca48a0df18a517b745445aa8706f",
    cancer_type: "Leukemia, Multiple Myeloma",
    location: "Blood, Bone",
    species: "Human",
    subject: 60,
    data_format: "BMP",
    supporting_data: "N/A",
    manufacturer: "Nikon",
    modality: "Raster",
    protocol: "Jenner-Giemsa stain",
    par: "",
    magnification: "1000x",
    size: 2.9,
    access: "Public",
    updated: "2019-05-28",
  },
  {
    collection: "Osteosarcoma-Tumor-Assessment",
    collection_url: "10.7937/tcia.2019.bvhjhdas",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:osteosarcoma_tumor_assessment",
    download: "Download",
    download_url: "70?passcode=93cc61a4c4ae53aa503b26d8c87badd592e75fd2",
    cancer_type: "Osteosarcoma",
    location: "Bone",
    species: "Human",
    subject: 4,
    data_format: "JPG",
    supporting_data: "Image Analyses",
    manufacturer: "Leica",
    modality: "Whole slide image",
    protocol: "Hematoxylin and eosin stain",
    par: "",
    magnification: "10x",
    size: 0.196,
    access: "Public",
    updated: "2019-03-26",
  },
  {
    collection: "Prostate Fused-MRI-Pathology",
    collection_url: "10.7937/K9/TCIA.2016.TLPMR1AM",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:prostate_fused_mri_pathology",
    download: "Download",
    download_url: "72?passcode=3da9391db835cc0937cd309ea568755c2153b056",
    cancer_type: "Prostate Cancer",
    location: "Prostate",
    species: "Human",
    subject: 28,
    data_format: "TIFF",
    supporting_data: "Image Analyses",
    manufacturer: "Leica",
    modality: "Whole mount histology",
    protocol: "Hematoxylin and eosin stain",
    par: "(0.500,0.500)mpp",
    magnification: "20x",
    size: 76.8,
    access: "Public",
    updated: "2016-11-30",
  },
  {
    collection: "Prostate-MRI",
    collection_url: "10.7937/K9/TCIA.2016.6046GUDv",
    view: "View",
    camic_url:
      "https://pathdb.cancerimagingarchive.net/imagesearch?f[0]=collection:prostate_mri",
    download: "Download",
    download_url: "60?passcode=685efef8b7729fb050f6877c3b08533819bcc28d",
    cancer_type: "Prostate Cancer",
    location: "Prostate",
    species: "Human",
    subject: 26,
    data_format: "JPG",
    supporting_data: "N/A",
    manufacturer: "",
    modality: "",
    protocol: "N/A",
    par: "",
    magnification: "",
    size: 0.206,
    access: "Public",
    updated: "2011-06-30",
  },
];
